name: Deploy to GitHub
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EMSCRIPTEN_VERSION: '3.1.29'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Compile grammar
        run: npm run generate
      - name: Build WASM binary
        run: npm run build-wasm
      - name: Deploy to GitHub Releases
        if: github.event_name != 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          artifacts: tree-sitter-kotlin.wasm
          token: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Update this to the new playground layout. This would
      #       involve deploying the Wasm binary to
      # 
      #         assets/tree-sitter-kotlin-<version>/tree-sitter-kotlin.wasm
      #
      #       and would also require rewriting the versions in the
      #       index.html (both the reference to the parser binary and the
      #       displayed version). Ideally this should be performed by a
      #       script that generates the index.html automatically. Perhaps
      #       we could even generate this to automatically download
      #       web-tree-sitter and maybe even generate playground.js from
      #       the upstream playground.
      #
      #       Also, we would likely want to replace peaceiris/actions-gh-pages
      #       with the `gh` command-line tool, which should already be
      #       preinstalled in the runner.

      # - name: Set up folder for GitHub Pages deployment
      #   run: |
      #     mkdir public
      #     cp tree-sitter-kotlin.wasm public/tree-sitter-parser.wasm
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     keep_files: true
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
